# Generated from a native autotools headless build of VICE 3.10: the objects
# linked into each program ('ar t' of every linked library), mapped back to
# their sources. arch/headless replaced by arch/amiga, C++ linenoise dropped.
# VICE_SRC must point to vice-3.10/src.
# Sources shared by x64, xvic, xplus4 and xpet: compiled once (object library).
set(VICE_COMMON_SRC
	# (src)
	${VICE_SRC}/alarm.c
	${VICE_SRC}/attach.c
	${VICE_SRC}/autostart-prg.c
	${VICE_SRC}/autostart.c
	${VICE_SRC}/cbmdos.c
	${VICE_SRC}/cbmimage.c
	${VICE_SRC}/charset.c
	${VICE_SRC}/clipboard.c
	${VICE_SRC}/cmdline.c
	${VICE_SRC}/color.c
	${VICE_SRC}/crc32.c
	${VICE_SRC}/crt.c
	${VICE_SRC}/debug.c
	${VICE_SRC}/dma.c
	${VICE_SRC}/event.c
	${VICE_SRC}/findpath.c
	${VICE_SRC}/fliplist.c
	${VICE_SRC}/gcr.c
	${VICE_SRC}/info.c
	${VICE_SRC}/init.c
	${VICE_SRC}/initcmdline.c
	${VICE_SRC}/interrupt.c
	${VICE_SRC}/kbdbuf.c
	${VICE_SRC}/keyboard.c
	${VICE_SRC}/keymap.c
	${VICE_SRC}/lib.c
	${VICE_SRC}/log.c
	${VICE_SRC}/m3u.c
	${VICE_SRC}/machine-bus.c
	${VICE_SRC}/machine.c
	${VICE_SRC}/main.c
	${VICE_SRC}/mainlock.c
	${VICE_SRC}/network.c
	${VICE_SRC}/opencbmlib.c
	${VICE_SRC}/palette.c
	${VICE_SRC}/profiler.c
	${VICE_SRC}/ram.c
	${VICE_SRC}/rawfile.c
	${VICE_SRC}/rawnet.c
	${VICE_SRC}/resources.c
	${VICE_SRC}/romset.c
	${VICE_SRC}/screenshot.c
	${VICE_SRC}/sha1.c
	${VICE_SRC}/snapshot.c
	${VICE_SRC}/socket.c
	${VICE_SRC}/sound.c
	${VICE_SRC}/sysfile.c
	${VICE_SRC}/traps.c
	${VICE_SRC}/util.c
	${VICE_SRC}/vicefeatures.c
	${VICE_SRC}/vsync.c
	${VICE_SRC}/zfile.c
	${VICE_SRC}/zipcode.c
	# arch/amiga
	${VICE_SRC}/arch/amiga/archdep.c
	${VICE_SRC}/arch/amiga/c128ui.c
	${VICE_SRC}/arch/amiga/c64dtvui.c
	${VICE_SRC}/arch/amiga/c64scui.c
	${VICE_SRC}/arch/amiga/cbm2ui.c
	${VICE_SRC}/arch/amiga/cbm5x0ui.c
	${VICE_SRC}/arch/amiga/console.c
	${VICE_SRC}/arch/amiga/kbd.c
	${VICE_SRC}/arch/amiga/main.c
	${VICE_SRC}/arch/amiga/mousedrv.c
	${VICE_SRC}/arch/amiga/petui.c
	${VICE_SRC}/arch/amiga/scpu64ui.c
	${VICE_SRC}/arch/amiga/ui.c
	${VICE_SRC}/arch/amiga/uimon.c
	${VICE_SRC}/arch/amiga/uistatusbar.c
	${VICE_SRC}/arch/amiga/video.c
	${VICE_SRC}/arch/amiga/vsidui.c
	${VICE_SRC}/arch/amiga/vsyncarch.c
	# arch/shared
	${VICE_SRC}/arch/shared/archdep_access.c
	${VICE_SRC}/arch/shared/archdep_boot_path.c
	${VICE_SRC}/arch/shared/archdep_cbmfont.c
	${VICE_SRC}/arch/shared/archdep_chdir.c
	${VICE_SRC}/arch/shared/archdep_close.c
	${VICE_SRC}/arch/shared/archdep_create_user_cache_dir.c
	${VICE_SRC}/arch/shared/archdep_create_user_config_dir.c
	${VICE_SRC}/arch/shared/archdep_create_user_state_dir.c
	${VICE_SRC}/arch/shared/archdep_current_dir.c
	${VICE_SRC}/arch/shared/archdep_default_autostart_disk_image_file_name.c
	${VICE_SRC}/arch/shared/archdep_default_fliplist_file_name.c
	${VICE_SRC}/arch/shared/archdep_default_joymap_file_name.c
	${VICE_SRC}/arch/shared/archdep_default_logfile.c
	${VICE_SRC}/arch/shared/archdep_default_logger.c
	${VICE_SRC}/arch/shared/archdep_default_portable_resource_file_name.c
	${VICE_SRC}/arch/shared/archdep_default_resource_file_name.c
	${VICE_SRC}/arch/shared/archdep_default_rtc_file_name.c
	${VICE_SRC}/arch/shared/archdep_default_sysfile_pathlist.c
	${VICE_SRC}/arch/shared/archdep_dir.c
	${VICE_SRC}/arch/shared/archdep_ethernet_available.c
	${VICE_SRC}/arch/shared/archdep_exit.c
	${VICE_SRC}/arch/shared/archdep_expand_path.c
	${VICE_SRC}/arch/shared/archdep_extra_title_text.c
	${VICE_SRC}/arch/shared/archdep_fdopen.c
	${VICE_SRC}/arch/shared/archdep_file_exists.c
	${VICE_SRC}/arch/shared/archdep_file_is_blockdev.c
	${VICE_SRC}/arch/shared/archdep_file_is_chardev.c
	${VICE_SRC}/arch/shared/archdep_file_size.c
	${VICE_SRC}/arch/shared/archdep_filename_parameter.c
	${VICE_SRC}/arch/shared/archdep_fix_permissions.c
	${VICE_SRC}/arch/shared/archdep_fix_streams.c
	${VICE_SRC}/arch/shared/archdep_fseeko.c
	${VICE_SRC}/arch/shared/archdep_ftello.c
	${VICE_SRC}/arch/shared/archdep_get_current_drive.c
	${VICE_SRC}/arch/shared/archdep_get_hvsc_dir.c
	${VICE_SRC}/arch/shared/archdep_get_runtime_info.c
	${VICE_SRC}/arch/shared/archdep_get_vice_datadir.c
	${VICE_SRC}/arch/shared/archdep_get_vice_docsdir.c
	${VICE_SRC}/arch/shared/archdep_get_vice_drivesdir.c
	${VICE_SRC}/arch/shared/archdep_get_vice_hotkeysdir.c
	${VICE_SRC}/arch/shared/archdep_get_vice_machinedir.c
	${VICE_SRC}/arch/shared/archdep_getcwd.c
	${VICE_SRC}/arch/shared/archdep_glob.c
	${VICE_SRC}/arch/shared/archdep_home_path.c
	${VICE_SRC}/arch/shared/archdep_icon_path.c
	${VICE_SRC}/arch/shared/archdep_is_haiku.c
	${VICE_SRC}/arch/shared/archdep_is_macos_bindist.c
	${VICE_SRC}/arch/shared/archdep_is_windows_nt.c
	${VICE_SRC}/arch/shared/archdep_kbd_get_host_mapping.c
	${VICE_SRC}/arch/shared/archdep_list_drives.c
	${VICE_SRC}/arch/shared/archdep_make_backup_filename.c
	${VICE_SRC}/arch/shared/archdep_mkdir.c
	${VICE_SRC}/arch/shared/archdep_mkstemp_fd.c
	${VICE_SRC}/arch/shared/archdep_open_default_log_file.c
	${VICE_SRC}/arch/shared/archdep_path_is_relative.c
	${VICE_SRC}/arch/shared/archdep_program_name.c
	${VICE_SRC}/arch/shared/archdep_program_path.c
	${VICE_SRC}/arch/shared/archdep_quote_parameter.c
	${VICE_SRC}/arch/shared/archdep_quote_unzip.c
	${VICE_SRC}/arch/shared/archdep_rawnet_capability.c
	${VICE_SRC}/arch/shared/archdep_real_path.c
	${VICE_SRC}/arch/shared/archdep_remove.c
	${VICE_SRC}/arch/shared/archdep_rename.c
	${VICE_SRC}/arch/shared/archdep_require_vkbd.c
	${VICE_SRC}/arch/shared/archdep_rmdir.c
	${VICE_SRC}/arch/shared/archdep_rtc_get_centisecond.c
	${VICE_SRC}/arch/shared/archdep_sanitize_filename.c
	${VICE_SRC}/arch/shared/archdep_set_current_drive.c
	${VICE_SRC}/arch/shared/archdep_set_openmp_wait_policy.c
	${VICE_SRC}/arch/shared/archdep_signals.c
	${VICE_SRC}/arch/shared/archdep_sleep.c
	${VICE_SRC}/arch/shared/archdep_socketpeek.c
	${VICE_SRC}/arch/shared/archdep_sound.c
	${VICE_SRC}/arch/shared/archdep_spawn.c
	${VICE_SRC}/arch/shared/archdep_startup_log_error.c
	${VICE_SRC}/arch/shared/archdep_stat.c
	${VICE_SRC}/arch/shared/archdep_tick.c
	${VICE_SRC}/arch/shared/archdep_tmpnam.c
	${VICE_SRC}/arch/shared/archdep_user_cache_path.c
	${VICE_SRC}/arch/shared/archdep_user_config_path.c
	${VICE_SRC}/arch/shared/archdep_user_state_path.c
	${VICE_SRC}/arch/shared/archdep_usleep.c
	${VICE_SRC}/arch/shared/archdep_xdg.c
	${VICE_SRC}/arch/shared/console.c
	${VICE_SRC}/arch/shared/coproc.c
	${VICE_SRC}/arch/shared/dynlib.c
	${VICE_SRC}/arch/shared/rawnetarch.c
	${VICE_SRC}/arch/shared/rawnetarch_tuntap.c
	${VICE_SRC}/arch/shared/rawnetarch_unix.c
	${VICE_SRC}/arch/shared/rs232dev.c
	${VICE_SRC}/arch/shared/signals.c
	# arch/shared/hwsiddrv
	${VICE_SRC}/arch/shared/hwsiddrv/hardsid-unix-drv.c
	${VICE_SRC}/arch/shared/hwsiddrv/hs-unix-linux.c
	# arch/shared/mididrv
	${VICE_SRC}/arch/shared/mididrv/midi-osx-drv.c
	${VICE_SRC}/arch/shared/mididrv/midi-unix-drv.c
	${VICE_SRC}/arch/shared/mididrv/midi-win32-drv.c
	# arch/shared/socketdrv
	${VICE_SRC}/arch/shared/socketdrv/socketdrv.c
	# arch/shared/sounddrv
	${VICE_SRC}/arch/shared/sounddrv/soundaiff.c
	${VICE_SRC}/arch/shared/sounddrv/sounddummy.c
	${VICE_SRC}/arch/shared/sounddrv/sounddump.c
	${VICE_SRC}/arch/shared/sounddrv/soundfs.c
	${VICE_SRC}/arch/shared/sounddrv/soundiff.c
	${VICE_SRC}/arch/shared/sounddrv/soundmovie.c
	${VICE_SRC}/arch/shared/sounddrv/soundvoc.c
	${VICE_SRC}/arch/shared/sounddrv/soundwav.c
	# core
	${VICE_SRC}/core/ata.c
	${VICE_SRC}/core/ciacore.c
	${VICE_SRC}/core/ciatimer.c
	${VICE_SRC}/core/cs8900.c
	${VICE_SRC}/core/flash040core.c
	${VICE_SRC}/core/flash800core.c
	${VICE_SRC}/core/fmopl.c
	${VICE_SRC}/core/i8255a.c
	${VICE_SRC}/core/m93c86.c
	${VICE_SRC}/core/mc6821core.c
	${VICE_SRC}/core/riotcore.c
	${VICE_SRC}/core/scsi.c
	${VICE_SRC}/core/ser-eeprom.c
	${VICE_SRC}/core/spi-flash.c
	${VICE_SRC}/core/spi-sdcard.c
	${VICE_SRC}/core/t6721.c
	${VICE_SRC}/core/tpicore.c
	${VICE_SRC}/core/viacore.c
	# core/rtc
	${VICE_SRC}/core/rtc/bq4830y.c
	${VICE_SRC}/core/rtc/ds1202_1302.c
	${VICE_SRC}/core/rtc/ds1216e.c
	${VICE_SRC}/core/rtc/ds12c887.c
	${VICE_SRC}/core/rtc/ds1307.c
	${VICE_SRC}/core/rtc/ds1602.c
	${VICE_SRC}/core/rtc/pcf8583.c
	${VICE_SRC}/core/rtc/rtc-58321a.c
	${VICE_SRC}/core/rtc/rtc-72421.c
	${VICE_SRC}/core/rtc/rtc.c
	# datasette
	${VICE_SRC}/datasette/datasette-sound.c
	${VICE_SRC}/datasette/datasette.c
	# diag
	${VICE_SRC}/diag/c64_diag_586220_harness.c
	# diskimage
	${VICE_SRC}/diskimage/diskimage.c
	${VICE_SRC}/diskimage/fsimage-check.c
	${VICE_SRC}/diskimage/fsimage-create.c
	${VICE_SRC}/diskimage/fsimage-dxx.c
	${VICE_SRC}/diskimage/fsimage-gcr.c
	${VICE_SRC}/diskimage/fsimage-p64.c
	${VICE_SRC}/diskimage/fsimage-probe.c
	${VICE_SRC}/diskimage/fsimage.c
	${VICE_SRC}/diskimage/realimage.c
	# drive
	${VICE_SRC}/drive/drive-check.c
	${VICE_SRC}/drive/drive-cmdline-options.c
	${VICE_SRC}/drive/drive-resources.c
	${VICE_SRC}/drive/drive-snapshot.c
	${VICE_SRC}/drive/drive-sound.c
	${VICE_SRC}/drive/drive-writeprotect.c
	${VICE_SRC}/drive/drive.c
	${VICE_SRC}/drive/drivecpu.c
	${VICE_SRC}/drive/drivecpu65c02.c
	${VICE_SRC}/drive/driveimage.c
	${VICE_SRC}/drive/drivemem.c
	${VICE_SRC}/drive/driverom.c
	${VICE_SRC}/drive/drivesync.c
	${VICE_SRC}/drive/rotation.c
	# drive/iec
	${VICE_SRC}/drive/iec/cia1571d.c
	${VICE_SRC}/drive/iec/cia1581d.c
	${VICE_SRC}/drive/iec/cmdhd.c
	${VICE_SRC}/drive/iec/fdd.c
	${VICE_SRC}/drive/iec/glue1571.c
	${VICE_SRC}/drive/iec/iec-cmdline-options.c
	${VICE_SRC}/drive/iec/iec-resources.c
	${VICE_SRC}/drive/iec/iec.c
	${VICE_SRC}/drive/iec/iecrom.c
	${VICE_SRC}/drive/iec/memiec.c
	${VICE_SRC}/drive/iec/pc8477.c
	${VICE_SRC}/drive/iec/via1d1541.c
	${VICE_SRC}/drive/iec/via4000.c
	${VICE_SRC}/drive/iec/wd1770.c
	# drive/iecieee
	${VICE_SRC}/drive/iecieee/iecieee.c
	${VICE_SRC}/drive/iecieee/via2d.c
	# drive/ieee
	${VICE_SRC}/drive/ieee/fdc.c
	${VICE_SRC}/drive/ieee/ieee-cmdline-options.c
	${VICE_SRC}/drive/ieee/ieee-resources.c
	${VICE_SRC}/drive/ieee/ieee.c
	${VICE_SRC}/drive/ieee/ieeerom.c
	${VICE_SRC}/drive/ieee/memieee.c
	${VICE_SRC}/drive/ieee/riot1d.c
	${VICE_SRC}/drive/ieee/riot2d.c
	${VICE_SRC}/drive/ieee/via1d2031.c
	# drive/tcbm
	${VICE_SRC}/drive/tcbm/glue1551.c
	${VICE_SRC}/drive/tcbm/mem1551.c
	${VICE_SRC}/drive/tcbm/tcbm-cmdline-options.c
	${VICE_SRC}/drive/tcbm/tcbm-resources.c
	${VICE_SRC}/drive/tcbm/tcbm.c
	${VICE_SRC}/drive/tcbm/tcbmrom.c
	${VICE_SRC}/drive/tcbm/tpid.c
	# fileio
	${VICE_SRC}/fileio/cbmfile.c
	${VICE_SRC}/fileio/fileio.c
	${VICE_SRC}/fileio/p00.c
	# fsdevice
	${VICE_SRC}/fsdevice/fsdevice-close.c
	${VICE_SRC}/fsdevice/fsdevice-cmdline-options.c
	${VICE_SRC}/fsdevice/fsdevice-filename.c
	${VICE_SRC}/fsdevice/fsdevice-flush.c
	${VICE_SRC}/fsdevice/fsdevice-open.c
	${VICE_SRC}/fsdevice/fsdevice-read.c
	${VICE_SRC}/fsdevice/fsdevice-resources.c
	${VICE_SRC}/fsdevice/fsdevice-write.c
	${VICE_SRC}/fsdevice/fsdevice.c
	# gfxoutputdrv
	${VICE_SRC}/gfxoutputdrv/artstudiodrv.c
	${VICE_SRC}/gfxoutputdrv/bmpdrv.c
	${VICE_SRC}/gfxoutputdrv/ffmpegexedrv.c
	${VICE_SRC}/gfxoutputdrv/gfxoutput.c
	${VICE_SRC}/gfxoutputdrv/godotdrv.c
	${VICE_SRC}/gfxoutputdrv/iffdrv.c
	${VICE_SRC}/gfxoutputdrv/koaladrv.c
	${VICE_SRC}/gfxoutputdrv/minipaintdrv.c
	${VICE_SRC}/gfxoutputdrv/nativedrv.c
	${VICE_SRC}/gfxoutputdrv/pcxdrv.c
	${VICE_SRC}/gfxoutputdrv/ppmdrv.c
	${VICE_SRC}/gfxoutputdrv/zmbvdrv.c
	# hvsc
	${VICE_SRC}/hvsc/base.c
	${VICE_SRC}/hvsc/bugs.c
	${VICE_SRC}/hvsc/main.c
	${VICE_SRC}/hvsc/psid.c
	${VICE_SRC}/hvsc/sldb.c
	${VICE_SRC}/hvsc/stil.c
	# imagecontents
	${VICE_SRC}/imagecontents/diskcontents-block.c
	${VICE_SRC}/imagecontents/diskcontents-iec.c
	${VICE_SRC}/imagecontents/diskcontents.c
	${VICE_SRC}/imagecontents/imagecontents.c
	${VICE_SRC}/imagecontents/tapecontents.c
	# joyport
	${VICE_SRC}/joyport/bbrtc.c
	${VICE_SRC}/joyport/cardkey.c
	${VICE_SRC}/joyport/coplin_keypad.c
	${VICE_SRC}/joyport/cx21.c
	${VICE_SRC}/joyport/cx85.c
	${VICE_SRC}/joyport/inception.c
	${VICE_SRC}/joyport/joyport.c
	${VICE_SRC}/joyport/joyport_diag_586220_harness.c
	${VICE_SRC}/joyport/joyport_io_sim.c
	${VICE_SRC}/joyport/joystick.c
	${VICE_SRC}/joyport/lightpen.c
	${VICE_SRC}/joyport/mouse.c
	${VICE_SRC}/joyport/mouse_1351.c
	${VICE_SRC}/joyport/mouse_neos.c
	${VICE_SRC}/joyport/mouse_paddle.c
	${VICE_SRC}/joyport/mouse_quadrature.c
	${VICE_SRC}/joyport/multijoy.c
	${VICE_SRC}/joyport/ninja_snespad.c
	${VICE_SRC}/joyport/paperclip2.c
	${VICE_SRC}/joyport/paperclip64.c
	${VICE_SRC}/joyport/paperclip64e.c
	${VICE_SRC}/joyport/paperclip64sc.c
	${VICE_SRC}/joyport/powerpad.c
	${VICE_SRC}/joyport/protopad.c
	${VICE_SRC}/joyport/rushware_keypad.c
	${VICE_SRC}/joyport/sampler2bit.c
	${VICE_SRC}/joyport/sampler4bit.c
	${VICE_SRC}/joyport/script64_dongle.c
	${VICE_SRC}/joyport/spaceballs.c
	${VICE_SRC}/joyport/trapthem_snespad.c
	${VICE_SRC}/joyport/vizawrite64_dongle.c
	${VICE_SRC}/joyport/waasoft_dongle.c
	# lib/libzmbv
	${VICE_SRC}/lib/libzmbv/zmbv.c
	${VICE_SRC}/lib/libzmbv/zmbv_avi.c
	# lib/p64
	${VICE_SRC}/lib/p64/p64.c
	# monitor
	${VICE_SRC}/monitor/asm6502.c
	${VICE_SRC}/monitor/asm6502dtv.c
	${VICE_SRC}/monitor/asm65816.c
	${VICE_SRC}/monitor/asm6809.c
	${VICE_SRC}/monitor/asmR65C02.c
	${VICE_SRC}/monitor/asmz80.c
	${VICE_SRC}/monitor/mon_assemble6502.c
	${VICE_SRC}/monitor/mon_assemble65816.c
	${VICE_SRC}/monitor/mon_assemble6809.c
	${VICE_SRC}/monitor/mon_assembleR65C02.c
	${VICE_SRC}/monitor/mon_assemblez80.c
	${VICE_SRC}/monitor/mon_breakpoint.c
	${VICE_SRC}/monitor/mon_command.c
	${VICE_SRC}/monitor/mon_disassemble.c
	${VICE_SRC}/monitor/mon_drive.c
	${VICE_SRC}/monitor/mon_file.c
	${VICE_SRC}/monitor/mon_lex.c
	${VICE_SRC}/monitor/mon_memmap.c
	${VICE_SRC}/monitor/mon_memory.c
	${VICE_SRC}/monitor/mon_parse.c
	${VICE_SRC}/monitor/mon_profile.c
	${VICE_SRC}/monitor/mon_register.c
	${VICE_SRC}/monitor/mon_register6502.c
	${VICE_SRC}/monitor/mon_register6502dtv.c
	${VICE_SRC}/monitor/mon_register65816.c
	${VICE_SRC}/monitor/mon_register6809.c
	${VICE_SRC}/monitor/mon_registerR65C02.c
	${VICE_SRC}/monitor/mon_registerz80.c
	${VICE_SRC}/monitor/mon_util.c
	${VICE_SRC}/monitor/monitor.c
	${VICE_SRC}/monitor/monitor_binary.c
	${VICE_SRC}/monitor/monitor_network.c
	# parallel
	${VICE_SRC}/parallel/parallel-trap.c
	${VICE_SRC}/parallel/parallel.c
	# printerdrv
	${VICE_SRC}/printerdrv/driver-select.c
	${VICE_SRC}/printerdrv/drv-1520.c
	${VICE_SRC}/printerdrv/drv-ascii.c
	${VICE_SRC}/printerdrv/drv-mps803.c
	${VICE_SRC}/printerdrv/drv-nl10.c
	${VICE_SRC}/printerdrv/drv-raw.c
	${VICE_SRC}/printerdrv/interface-serial.c
	${VICE_SRC}/printerdrv/interface-userport.c
	${VICE_SRC}/printerdrv/output-graphics.c
	${VICE_SRC}/printerdrv/output-select.c
	${VICE_SRC}/printerdrv/output-text.c
	${VICE_SRC}/printerdrv/printer-serial.c
	${VICE_SRC}/printerdrv/printer-userport.c
	${VICE_SRC}/printerdrv/printer.c
	# raster
	${VICE_SRC}/raster/raster-cache.c
	${VICE_SRC}/raster/raster-canvas.c
	${VICE_SRC}/raster/raster-changes.c
	${VICE_SRC}/raster/raster-cmdline-options.c
	${VICE_SRC}/raster/raster-line-changes-sprite.c
	${VICE_SRC}/raster/raster-line-changes.c
	${VICE_SRC}/raster/raster-line.c
	${VICE_SRC}/raster/raster-modes.c
	${VICE_SRC}/raster/raster-resources.c
	${VICE_SRC}/raster/raster-snapshot.c
	${VICE_SRC}/raster/raster-sprite-cache.c
	${VICE_SRC}/raster/raster-sprite-status.c
	${VICE_SRC}/raster/raster-sprite.c
	${VICE_SRC}/raster/raster.c
	# rs232drv
	${VICE_SRC}/rs232drv/rs232.c
	${VICE_SRC}/rs232drv/rs232drv.c
	${VICE_SRC}/rs232drv/rs232net.c
	# samplerdrv
	${VICE_SRC}/samplerdrv/file_drv.c
	${VICE_SRC}/samplerdrv/portaudio_drv.c
	${VICE_SRC}/samplerdrv/sampler.c
	# serial
	${VICE_SRC}/serial/fsdrive.c
	${VICE_SRC}/serial/iec-ieee488-shared.c
	${VICE_SRC}/serial/realdevice.c
	${VICE_SRC}/serial/serial-device.c
	${VICE_SRC}/serial/serial-iec-bus.c
	${VICE_SRC}/serial/serial-iec-device.c
	${VICE_SRC}/serial/serial-iec-lib.c
	${VICE_SRC}/serial/serial-iec.c
	${VICE_SRC}/serial/serial-realdevice.c
	${VICE_SRC}/serial/serial-trap.c
	${VICE_SRC}/serial/serial.c
	# sid
	${VICE_SRC}/sid/catweaselmkiii.c
	${VICE_SRC}/sid/fastsid.c
	${VICE_SRC}/sid/hardsid.c
	${VICE_SRC}/sid/parsid.c
	${VICE_SRC}/sid/sid-cmdline-options.c
	${VICE_SRC}/sid/sid-resources.c
	${VICE_SRC}/sid/sid-snapshot.c
	${VICE_SRC}/sid/sid.c
	${VICE_SRC}/sid/usbsid.c
	# tape
	${VICE_SRC}/tape/t64.c
	${VICE_SRC}/tape/tap.c
	${VICE_SRC}/tape/tape-internal.c
	${VICE_SRC}/tape/tape-snapshot.c
	${VICE_SRC}/tape/tape.c
	${VICE_SRC}/tape/tapeimage.c
	# tapeport
	${VICE_SRC}/tapeport/cp-clockf83.c
	${VICE_SRC}/tapeport/dtl-basic-dongle.c
	${VICE_SRC}/tapeport/sense-dongle.c
	${VICE_SRC}/tapeport/tape_diag_586220_harness.c
	${VICE_SRC}/tapeport/tapecart.c
	${VICE_SRC}/tapeport/tapeport.c
	${VICE_SRC}/tapeport/wordcraft-dongle.c
	# userport
	${VICE_SRC}/userport/userport.c
	${VICE_SRC}/userport/userport_4bit_sampler.c
	${VICE_SRC}/userport/userport_8bss.c
	${VICE_SRC}/userport/userport_dac.c
	${VICE_SRC}/userport/userport_diag_586220_harness.c
	${VICE_SRC}/userport/userport_diag_pin.c
	${VICE_SRC}/userport/userport_digimax.c
	${VICE_SRC}/userport/userport_funmp3.c
	${VICE_SRC}/userport/userport_hks_joystick.c
	${VICE_SRC}/userport/userport_hummer_joystick.c
	${VICE_SRC}/userport/userport_io_sim.c
	${VICE_SRC}/userport/userport_joystick.c
	${VICE_SRC}/userport/userport_petscii_snespad.c
	${VICE_SRC}/userport/userport_ps2mouse.c
	${VICE_SRC}/userport/userport_rtc_58321a.c
	${VICE_SRC}/userport/userport_rtc_ds1307.c
	${VICE_SRC}/userport/userport_spt_joystick.c
	${VICE_SRC}/userport/userport_superpad64.c
	${VICE_SRC}/userport/userport_synergy_joystick.c
	${VICE_SRC}/userport/userport_wic64.c
	${VICE_SRC}/userport/userport_woj_joystick.c
	# vdrive
	${VICE_SRC}/vdrive/vdrive-bam.c
	${VICE_SRC}/vdrive/vdrive-command.c
	${VICE_SRC}/vdrive/vdrive-dir.c
	${VICE_SRC}/vdrive/vdrive-iec.c
	${VICE_SRC}/vdrive/vdrive-internal.c
	${VICE_SRC}/vdrive/vdrive-rel.c
	${VICE_SRC}/vdrive/vdrive-snapshot.c
	${VICE_SRC}/vdrive/vdrive.c
	# video
	${VICE_SRC}/video/render1x1.c
	${VICE_SRC}/video/render1x1ntsc.c
	${VICE_SRC}/video/render1x1pal.c
	${VICE_SRC}/video/render1x1rgbi.c
	${VICE_SRC}/video/render1x2.c
	${VICE_SRC}/video/render1x2rgbi.c
	${VICE_SRC}/video/render2x2.c
	${VICE_SRC}/video/render2x2ntsc.c
	${VICE_SRC}/video/render2x2pal.c
	${VICE_SRC}/video/render2x2palu.c
	${VICE_SRC}/video/render2x2rgbi.c
	${VICE_SRC}/video/render2x4.c
	${VICE_SRC}/video/render2x4rgbi.c
	${VICE_SRC}/video/renderscale2x.c
	${VICE_SRC}/video/video-canvas.c
	${VICE_SRC}/video/video-cmdline-options.c
	${VICE_SRC}/video/video-color.c
	${VICE_SRC}/video/video-render-crtmono.c
	${VICE_SRC}/video/video-render-palntsc.c
	${VICE_SRC}/video/video-render-rgbi.c
	${VICE_SRC}/video/video-render.c
	${VICE_SRC}/video/video-resources.c
	${VICE_SRC}/video/video-sound.c
	${VICE_SRC}/video/video-viewport.c
)
