# Generated from a native autotools headless build of VICE 3.10: the objects
# linked into each program ('ar t' of every linked library), mapped back to
# their sources. arch/headless replaced by arch/amiga, C++ linenoise dropped.
# VICE_SRC must point to vice-3.10/src.
# Sources only used by the C64 (x64) emulator, on top of VICE_COMMON_SRC.
set(VICE_X64_SRC
	# c64
	${VICE_SRC}/c64/c64-cmdline-options.c
	${VICE_SRC}/c64/c64-memory-hacks.c
	${VICE_SRC}/c64/c64-resources.c
	${VICE_SRC}/c64/c64-snapshot.c
	${VICE_SRC}/c64/c64-stubs.c
	${VICE_SRC}/c64/c64.c
	${VICE_SRC}/c64/c64_256k.c
	${VICE_SRC}/c64/c64bus.c
	${VICE_SRC}/c64/c64cia1.c
	${VICE_SRC}/c64/c64cia2.c
	${VICE_SRC}/c64/c64cpu.c
	${VICE_SRC}/c64/c64datasette.c
	${VICE_SRC}/c64/c64drive.c
	${VICE_SRC}/c64/c64export.c
	${VICE_SRC}/c64/c64fastiec.c
	${VICE_SRC}/c64/c64gluelogic.c
	${VICE_SRC}/c64/c64iec.c
	${VICE_SRC}/c64/c64io.c
	${VICE_SRC}/c64/c64keyboard.c
	${VICE_SRC}/c64/c64mem.c
	${VICE_SRC}/c64/c64meminit.c
	${VICE_SRC}/c64/c64memlimit.c
	${VICE_SRC}/c64/c64memrom.c
	${VICE_SRC}/c64/c64memsnapshot.c
	${VICE_SRC}/c64/c64model.c
	${VICE_SRC}/c64/c64parallel.c
	${VICE_SRC}/c64/c64pla.c
	${VICE_SRC}/c64/c64printer.c
	${VICE_SRC}/c64/c64rom.c
	${VICE_SRC}/c64/c64romset.c
	${VICE_SRC}/c64/c64rsuser.c
	${VICE_SRC}/c64/c64sound.c
	${VICE_SRC}/c64/c64video.c
	${VICE_SRC}/c64/plus256k.c
	${VICE_SRC}/c64/plus60k.c
	# c64/cart
	${VICE_SRC}/c64/cart/actionreplay.c
	${VICE_SRC}/c64/cart/actionreplay2.c
	${VICE_SRC}/c64/cart/actionreplay3.c
	${VICE_SRC}/c64/cart/actionreplay4.c
	${VICE_SRC}/c64/cart/atomicpower.c
	${VICE_SRC}/c64/cart/bisplus.c
	${VICE_SRC}/c64/cart/blackbox3.c
	${VICE_SRC}/c64/cart/blackbox4.c
	${VICE_SRC}/c64/cart/blackbox8.c
	${VICE_SRC}/c64/cart/blackbox9.c
	${VICE_SRC}/c64/cart/bmpdataturbo.c
	${VICE_SRC}/c64/cart/c64-generic.c
	${VICE_SRC}/c64/cart/c64-midi.c
	${VICE_SRC}/c64/cart/c64acia1.c
	${VICE_SRC}/c64/cart/c64cart.c
	${VICE_SRC}/c64/cart/c64carthooks.c
	${VICE_SRC}/c64/cart/c64cartmem.c
	${VICE_SRC}/c64/cart/c64tpi.c
	${VICE_SRC}/c64/cart/capture.c
	${VICE_SRC}/c64/cart/clockport-mp3at64.c
	${VICE_SRC}/c64/cart/clockport-rrnet.c
	${VICE_SRC}/c64/cart/clockport.c
	${VICE_SRC}/c64/cart/comal80.c
	${VICE_SRC}/c64/cart/cpmcart.c
	${VICE_SRC}/c64/cart/cs8900io.c
	${VICE_SRC}/c64/cart/daa.c
	${VICE_SRC}/c64/cart/debugcart.c
	${VICE_SRC}/c64/cart/delaep256.c
	${VICE_SRC}/c64/cart/delaep64.c
	${VICE_SRC}/c64/cart/delaep7x8.c
	${VICE_SRC}/c64/cart/diashowmaker.c
	${VICE_SRC}/c64/cart/digimax.c
	${VICE_SRC}/c64/cart/dinamic.c
	${VICE_SRC}/c64/cart/dqbb.c
	${VICE_SRC}/c64/cart/drean.c
	${VICE_SRC}/c64/cart/ds12c887rtc.c
	${VICE_SRC}/c64/cart/easycalc.c
	${VICE_SRC}/c64/cart/easyflash.c
	${VICE_SRC}/c64/cart/epyxfastload.c
	${VICE_SRC}/c64/cart/ethernetcart.c
	${VICE_SRC}/c64/cart/exos.c
	${VICE_SRC}/c64/cart/expert.c
	${VICE_SRC}/c64/cart/final.c
	${VICE_SRC}/c64/cart/final3.c
	${VICE_SRC}/c64/cart/finalplus.c
	${VICE_SRC}/c64/cart/formel64.c
	${VICE_SRC}/c64/cart/freezeframe.c
	${VICE_SRC}/c64/cart/freezeframe2.c
	${VICE_SRC}/c64/cart/freezemachine.c
	${VICE_SRC}/c64/cart/funplay.c
	${VICE_SRC}/c64/cart/gamekiller.c
	${VICE_SRC}/c64/cart/georam.c
	${VICE_SRC}/c64/cart/gmod2.c
	${VICE_SRC}/c64/cart/gmod3.c
	${VICE_SRC}/c64/cart/gs.c
	${VICE_SRC}/c64/cart/hyperbasic.c
	${VICE_SRC}/c64/cart/ide64.c
	${VICE_SRC}/c64/cart/ieeeflash64.c
	${VICE_SRC}/c64/cart/isepic.c
	${VICE_SRC}/c64/cart/kcs.c
	${VICE_SRC}/c64/cart/kingsoft.c
	${VICE_SRC}/c64/cart/ltkernal.c
	${VICE_SRC}/c64/cart/mach5.c
	${VICE_SRC}/c64/cart/magicdesk.c
	${VICE_SRC}/c64/cart/magicdesk16.c
	${VICE_SRC}/c64/cart/magicformel.c
	${VICE_SRC}/c64/cart/magicvoice.c
	${VICE_SRC}/c64/cart/maxbasic.c
	${VICE_SRC}/c64/cart/megabyter.c
	${VICE_SRC}/c64/cart/mikroass.c
	${VICE_SRC}/c64/cart/mmc64.c
	${VICE_SRC}/c64/cart/mmcreplay.c
	${VICE_SRC}/c64/cart/multimax.c
	${VICE_SRC}/c64/cart/ocean.c
	${VICE_SRC}/c64/cart/pagefox.c
	${VICE_SRC}/c64/cart/partner64.c
	${VICE_SRC}/c64/cart/profidos.c
	${VICE_SRC}/c64/cart/prophet64.c
	${VICE_SRC}/c64/cart/ramcart.c
	${VICE_SRC}/c64/cart/ramlink.c
	${VICE_SRC}/c64/cart/retroreplay.c
	${VICE_SRC}/c64/cart/reu.c
	${VICE_SRC}/c64/cart/rexep256.c
	${VICE_SRC}/c64/cart/rexramfloppy.c
	${VICE_SRC}/c64/cart/rexutility.c
	${VICE_SRC}/c64/cart/rgcd.c
	${VICE_SRC}/c64/cart/ross.c
	${VICE_SRC}/c64/cart/rrnetmk3.c
	${VICE_SRC}/c64/cart/sdbox.c
	${VICE_SRC}/c64/cart/sfx_soundexpander.c
	${VICE_SRC}/c64/cart/sfx_soundsampler.c
	${VICE_SRC}/c64/cart/shortbus.c
	${VICE_SRC}/c64/cart/shortbus_digimax.c
	${VICE_SRC}/c64/cart/shortbus_etfe.c
	${VICE_SRC}/c64/cart/silverrock128.c
	${VICE_SRC}/c64/cart/simonsbasic.c
	${VICE_SRC}/c64/cart/snapshot64.c
	${VICE_SRC}/c64/cart/stardos.c
	${VICE_SRC}/c64/cart/stb.c
	${VICE_SRC}/c64/cart/superexplode5.c
	${VICE_SRC}/c64/cart/supergames.c
	${VICE_SRC}/c64/cart/supersnapshot.c
	${VICE_SRC}/c64/cart/supersnapshot4.c
	${VICE_SRC}/c64/cart/turtlegraphics.c
	${VICE_SRC}/c64/cart/uc1.c
	${VICE_SRC}/c64/cart/uc2.c
	${VICE_SRC}/c64/cart/warpspeed.c
	${VICE_SRC}/c64/cart/westermann.c
	${VICE_SRC}/c64/cart/zaxxon.c
	${VICE_SRC}/c64/cart/zippcode48.c
	# drive/iec/c64exp
	${VICE_SRC}/drive/iec/c64exp/c64exp-cmdline-options.c
	${VICE_SRC}/drive/iec/c64exp/c64exp-resources.c
	${VICE_SRC}/drive/iec/c64exp/dolphindos3.c
	${VICE_SRC}/drive/iec/c64exp/iec-c64exp.c
	${VICE_SRC}/drive/iec/c64exp/profdos.c
	${VICE_SRC}/drive/iec/c64exp/stardos-exp.c
	${VICE_SRC}/drive/iec/c64exp/supercard.c
	# iecbus
	${VICE_SRC}/iecbus/iecbus.c
	# (src)
	${VICE_SRC}/midi.c
	# rs232drv
	${VICE_SRC}/rs232drv/rsuser.c
	# vicii
	${VICE_SRC}/vicii/vicii-badline.c
	${VICE_SRC}/vicii/vicii-clock-stretch.c
	${VICE_SRC}/vicii/vicii-cmdline-options.c
	${VICE_SRC}/vicii/vicii-color.c
	${VICE_SRC}/vicii/vicii-draw.c
	${VICE_SRC}/vicii/vicii-fetch.c
	${VICE_SRC}/vicii/vicii-irq.c
	${VICE_SRC}/vicii/vicii-mem.c
	${VICE_SRC}/vicii/vicii-phi1.c
	${VICE_SRC}/vicii/vicii-resources.c
	${VICE_SRC}/vicii/vicii-snapshot.c
	${VICE_SRC}/vicii/vicii-sprites.c
	${VICE_SRC}/vicii/vicii-stubs.c
	${VICE_SRC}/vicii/vicii-timing.c
	${VICE_SRC}/vicii/vicii.c
)
