Guess the number: DO ... LOOP, IF ... ELSE.
Plus/4 BASIC 3.5, from BASICv3Quick.guide, example 2.

10 X=RND(-TI) : N=INT(RND(1)*100)+1 : T=0
20 SCNCLR : PRINT "I THINK OF A NUMBER, 1 TO 100"
30 DO
40 INPUT "YOUR GUESS";G : T=T+1
50 IF G<N THEN PRINT "TOO LOW" : ELSE IF G>N THEN PRINT "TOO HIGH"
60 LOOP UNTIL G=N
70 PRINT "FOUND IN";T;"TRIES"
